apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        resources: {}
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: admin
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: password
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongo-sv
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-express-sv
spec:
  selector:
    app: mongo-express
  ports:
  - port: 8081
    targetPort: 8081
  type: LoadBalancer
